#* Not tested!
sudo: required
services:
  - docker

before_install:
  - docker build -t docker_hub_id/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run docker_hub_id/react-test npm test -- --coverage

after_success:
  - docker build -t docker_hub_id/multi-client ./client
  - docker build -t docker_hub_id/multi-nginx ./nginx
  - docker build -t docker_hub_id/multi-server ./server
  - docker build -t docker_hub_id/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push docker_hub_id/multi-client
  - docker push docker_hub_id/multi-nginx
  - docker push docker_hub_id/multi-server
  - docker push docker_hub_id/multi-worker

deploy:
  provider: elasticbeanstalk
  region: region
  app: multi-docker
  env: MultiDocker-env
  bucket_name: bucket_name
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
