sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t docker_username/repo_name -f Dockerfile.dev .

script:
  - docker run -e CI=true docker_username/repo_name npm run test

deploy:
  provider: elasticbeanstalk
  region: "region"
  app: "docker"
  env: "docker-env"
  bucket_name: "bucket_name"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
